### ISSUE TITLE
Cannot build without having first run 'mvn install'

### ISSUE THREAD

**Issue by rmtmckenzie** [smoope/j2objc-maven-plugin#10]
Until I run mvn install, dependency resolution is complaining about not finding the package I'm trying to build in the repository.

I'm not planning on doing my project build with maven but rather just j2objc, which has different dependencies than building the java code. So unless the build really needs the locally installed version it'd be much more convenient if I didn't have to build it first.

This is the example project:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>mavenproject1</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>
    
    
    <build>
        <plugins>
        
            <plugin>
                <groupId>com.smoope.utils</groupId>
                <artifactId>j2objc-maven-plugin</artifactId>
                <version>1.1.2</version>
                <configuration>
                    <j2objcPath>${J2OBJC_DISTRIBUTION}</j2objcPath>
                    <swiftFriendly>true</swiftFriendly>
                </configuration>
            </plugin>

        </plugins>
    </build>
    
</project>
```

And this is the exception:
`
org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact com.mycompany:mavenproject1:jar:1.0-SNAPSHOT
`

Also, if the build absolutely needs to be in the local repository for some reason, it might be worth mentioning it in the readme.

**Comment by vicmosin** [comment]
Hi there,
well, if I understand your issue correct, you want to be able to run plugin without/before publishing the artifact into your local repository, I am correct?

**Comment by rmtmckenzie** [comment]
Yes, that's correct. Basically, I have a fairly specific gradle set-up I use for building, but the gradle plugin for j2objc isn't really operable at the moment and I don't have time to invest in sorting that out right now, so I'm using maven to build the objc instead. But I don't particularly want to have to do/maintain the full java build & install with maven as well as the gradle. 

If that would require major changes to anything don't worry about it; I'm probably in a very small minority of use-cases and realistically if the gradle plugin were in better shape it wouldn't be an issue in the first place. And it's definitely not blocking me in any way. But from the quick look I took at the source of the maven plugin (keeping in mind that I'm much more familiar with gradle...) it looked like it was simply using the installed artifact for its pom & maybe dependency resolution rather than actually needed it.

Either way, thanks for your time =)

**Comment by vicmosin** [comment]
But in this case it's much easier for you to use a library itself rather than dealing with maven plugin.. epsecially if you use gradle as a build engine in your project. btw I remember there was a gradle plugin as well, it motivated me actually to develop a maven plugin:-)

Good luck!
