### ISSUE TITLE
Feature - build dependencies without executing local project src/main/java folder

### ISSUE THREAD

**Issue by shutter92** [smoope/j2objc-maven-plugin#12]
Hi,

I have the issue that when i want to build the objectiveC sources from the java third party libary sources in my parent.pom file the execution fails because in my parent project is no src/main/java directory.
My goals is to build all third party dependencies in the parent.pom once without running j2objc  for the local src/main/java directory. So maybe someone can add a additional flag for that issue because i am not familiar with forking this project and uploading the plugin to the central maven repository.

If there is already a solution for my issue, please let me know.

**Comment by vicmosin** [comment]
Hi @shutter92 ,
could you please try to specify `sourcePath` param, be default it points to `/src/main/java` and you can put any path you want

**Comment by shutter92** [comment]
Hi thanks for the fast reply, but my problem is that I want to say the plugin that it should skip searching for the src/main/java directory. If I leave it blank or don't specify it, it always searches for the the default maven path. So my goal is to skip searching for the path in my parent pom file and then compile the sources of the third party libs with this plugin.

**Comment by vicmosin** [comment]
Ok, now I see. Can't you just create an empty project and specify dependencies in pom file? Did you try it already?

**Comment by vicmosin** [comment]
@shutter92 
I pushed `1.1.4-SNAPSHOT` contains new `dependenciesOnly` param. Default is false, could you try it please?

**Comment by shutter92** [comment]
I didn't tried it with an empty project but it should work. In my opinion this is not the best solution to fix the use case.

Thanks I will try it later.

**Comment by shutter92** [comment]
@vicmosin 
It works for me. Thanks a lot:)
