### ISSUE TITLE
Feature request: Add <source>-Tag to enable lambdas

### ISSUE THREAD

**Issue by dholzenburg** [smoope/j2objc-maven-plugin#2]
Hi Victor,

sorry for bothering again :-) 

I want / need to use lambdas which is supported by j2objc when specifying the -source option (-source 8 in this case).

Unfortunately it is not possible to specify the <source> option in pom.xml.

Would you be so kind to add this to the plugin? I think in pom.xml it should be possible to specify something like this:

 ```
<plugin>
  <groupId>com.smoope.utils</groupId>
  <artifactId>j2objc-maven-plugin</artifactId>
  <version>1.0.1-SNAPSHOT</version>
  <configuration>
    <j2objcPath>/usr/local/j2objc/j2objc</j2objcPath>
    <source>8</source>
    ...
  </configuration>
</plugin>
```

Thank you very much in advance!

Regards, Dirk

**Comment by vicmosin** [comment]
I relied on official docs, there was no such option there...
Please check `1.1.0-SNAPSHOT`, I'll add all undocumented options there.

**Comment by dholzenburg** [comment]
Thank you very much again. Works like a charm...
