### ISSUE TITLE
extractJar() fails if source jar file does not contain directory entries

### ISSUE THREAD

**Issue by dholzenburg** [smoope/j2objc-maven-plugin#3]
Hi again,

I have a jar file which does not contain any directory entries, just the file entries. This results in a FileNotFoundException when trying to write the JarEntry to a file. 

This is the jar that fails:
```
<dependency>
  <groupId>com.google.web.bindery</groupId>
  <artifactId>requestfactory-client</artifactId>
  <version>2.8.0-beta1</version>
</dependency>
```

My suggestion: Catch the FileNotFoundException, create the parent directories and try again.

My suggested code snippet:
```
...
Enumeration enumEntries = jarFile.entries();
while (enumEntries.hasMoreElements()) {
  JarEntry jarEntry = (JarEntry) enumEntries.nextElement();
  File f = new File(output, jarEntry.getName());
  if (jarEntry.isDirectory()) {
    f.mkdir();
  } else {
    InputStream is = jarFile.getInputStream(jarEntry);
    while (true) {
      try {
        //try to create output file, it may fail if parent directories have not been created before
        FileOutputStream fos = new FileOutputStream(f);
        while (is.available() > 0) {
          fos.write(is.read());
        }
        fos.close();
        break; //this has been successful so we can leave the loop
      } catch (final FileNotFoundException ex) {
        new File(f.getParent()).mkdirs(); //create parent directories and try again
      }
    }
    is.close();
  }
}
...
```

It would be great if you could fix this issue either with this code snippet or some other solution.

Thank you very much in advance (again)!

**Comment by vicmosin** [comment]
I pushed `1.1.1-SNAPSHOT` with the fix. But it seems that j2objc itself fails with requestfactory-client after all:
```
java.lang.NullPointerException
[ERROR] 	at com.google.devtools.j2objc.translate.GwtConverter.visit(GwtConverter.java:89)
```
Let me please know if you can solve it.

**Comment by dholzenburg** [comment]
I am getting the same error and I will ask the j2objc about that one.

Anyway, version 1.1.1-SNAPSHOT of this plugin works fine now, so you may close this issue. Thank you very much again!

**Comment by vicmosin** [comment]
Could you please post here the link to j2objc-related issue

**Comment by dholzenburg** [comment]
Link of j2objc-related issue: https://github.com/google/j2objc/issues/689
