### ISSUE TITLE
.java files should not be added to command with absolute paths (especially when using --preserve-full-paths)

### ISSUE THREAD

**Issue by dholzenburg** [smoope/j2objc-maven-plugin#4]
Hi again,

I tried the `--preserve-full-paths` (`<preserveFullPaths>true</preserveFullPaths>`) option, but it produces wrong results when using the plugin.

In my target directory the whole absolute path of my files are created instead of just starting from the package directories. 

Current behaviour: `/Users/me/my/path/to/project/target/j2objc/Users/me/my/path/to/project/src/main/java/some/package/name/file.h`

Expected:
`/Users/me/my/path/to/project/target/j2objc/some/package/name/file.h`
 
Since `-sourcepath` is used and refers to `${project.basedir}/src/main/java` file names should be added like this: `some/package/name/file.java` instead of `/Users/me/my/path/to/project/src/main/java/some/package/name/file.java`

Is this a bug or am I just doing something wrong?

**Comment by vicmosin** [comment]
HI, 
I am not sure if it can be called a bug.. Official docs says: "Generates output files with the same relative paths as the input files." but in our case we can't provide source files directly, plugin does it for us. Anyway, I changed the logics so now all the source files passed to j2objc are relative to `sourcePath` path, which means to `${project.basedir}/src/main/java`. In case of dependencies it also tries to use relative path (per each dependency).
Please try `1.1.2-SNAPSHOT`

**Comment by dholzenburg** [comment]
Thank you very much for the quick response. Unfortunately I cannot check before tomorrow.

**Comment by dholzenburg** [comment]
I finally checked the new version and it works perfectly. Thank you very much!
