### ISSUE TITLE
Maven Project Build Lifecycle Mapping Problem with Eclipse

### ISSUE THREAD

**Issue by donat-mueller** [smoope/j2objc-maven-plugin#9]
Hi all
First thanks to smoope and the contributors of this plugin.
I am from the project PDFReporter (jasper report library fork for Android and iOS offline reporting) and  have a little issue that may confuse some users.
Have a multi module maven project with the following parent pom.xml
```
...
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>com.smoope.utils</groupId>
					<artifactId>j2objc-maven-plugin</artifactId>
					<version>${j2objc-plugin.version}</version>
					<executions>
						<execution>
							<phase>compile</phase>
							<goals>
								<goal>convert</goal>
							</goals>
						</execution>
					</executions>
					<configuration>
...

...
	<properties>
		<junit.version>4.11</junit.version>
		<java.version>1.7</java.version>
		<j2objc-plugin.version>1.1.3-SNAPSHOT</j2objc-plugin.version>
...

```
In the modules that require transpiling java sources I add:
```
			<plugin>
				<groupId>com.smoope.utils</groupId>
				<artifactId>j2objc-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>convert</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

```
All works fine for cmd line maven build with maven 3.3.1 and j2objc-maven-plugin:1.1.3-SNAPSHOT but in eclipse I get the following Problems with maven pom.xml validation:
`Error (1 item)
Plugin execution not covered by lifecycle configuration: com.smoope.utils:j2objc-maven-plugin:1.1.3-SNAPSHOT:convert (execution: default, phase: compile)	pom.xml	/api	line 17	Maven Project Build Lifecycle Mapping Problem` in the module api for example. 

Then in eclipse with RunAs -> maven install
```
[ERROR] urls[28] = file:/Users/donatmueller/.m2/repository/org/slf4j/jcl-over-slf4j/1.6.2/jcl-over-slf4j-1.6.2.jar
[ERROR] urls[29] = file:/Users/donatmueller/.m2/repository/org/slf4j/slf4j-api/1.6.2/slf4j-api-1.6.2.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.eclipse.aether.spi.connector.transport.TransporterFactory
[ERROR] -> [Help 1]

```
thought the later is solved with the 1.1.3-SNAPSHOT version. See closed issue [Failing on Aether](https://github.com/smoope/j2objc-maven-plugin/issues/5).

Can anybody give me a hint ?

**Comment by donat-mueller** [comment]
Btw: noticed that a transpiling error will cause maven to fail with 1.1.3-SNAPSHOT but not with 1.1.2 release. Is this a feature or a bug ?

**Comment by vicmosin** [comment]
@donat-mueller thanks for reporting! we glad that plugin help people.
As far as I understood with 3.3.1 everything works fine from CLI, but in eclipse there are some issues. Could first of all make sure that your eclipse instance points exactly to the same 3.3.1?
If it still there, could you provide an example of pom you want to convert with plugin? Will try to reproduce it locally..

**Comment by TallDaveWeiss** [comment]
@donat-mueller The failure of the build on transpiling errors was from https://github.com/smoope/j2objc-maven-plugin/pull/7.  I think if this is a problem, we should add an option to the plugin "fail-on-errors".  For me, if the code I wrote could not be transpiled into ObjC, the code was wrong, so I wanted a failure rather than thinking all was well.

**Comment by vicmosin** [comment]
@donat-mueller are you fine with @TallDaveWeiss 's suggestion?

**Comment by donat-mueller** [comment]
@vicmosin yes for TallDaveWeiss and I agree that its up to me to put only those files on the transpilepath that can be transpiled. 
About Eclipse IDE build thx for the hint after configuring eclipse using the same maven installation as CLI it builds without errors. One thing remains the editor validation of the pom.xml, where the execution goal is convert.
```
Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: com.smoope.utils:j2objc-maven-plugin:1.1.2:convert (execution: default, phase: compile)	pom.xml	/api	line 17	Maven Project Build Lifecycle Mapping Problem
```
Should I leave goal to default ?

**Comment by vicmosin** [comment]
@donat-mueller 
I've added new config option `failOnErrors` (default is `true`) as suggested and  1.1.3-SNAPSHOT so please try it.

**Comment by donat-mueller** [comment]
Sorry for late reply. The `failOnErrors` option works fine.
For the execution goal `package` makes sense as it happens before integration-test where the tests of transpiled code should be executed.
